### ISSUE TITLE
A issue/question on CTimer.to_sec()

### ISSUE THREAD

**Issue by zyguan** [PanRui1123/TimeDuration#1]
Hi, @PanRui1123, why multiple 1e6 [here](https://github.com/PanRui1123/TimeDuration/blob/master/src/CTimer.hpp#L25)?

**Comment by PanRui1123** [comment]
in fact it's false. thanks a lot and i'd like update it later. The intention of this lib is just I need a lib to record running time. = =|||

**Comment by zyguan** [comment]
got it :)
